import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';
import './globals.css';
import { Provider } from '@/Provider';
import { AntdRegistry } from '@/lib/antd-registry';
import { Toaster } from 'sonner';
import { ConfigProvider } from 'antd';
import { mainTheme } from '@/lib/theme/ant-theme';

const jakarta = Plus_Jakarta_Sans({
  variable: '--font-plus-jakarta',
  // weight: ['200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Steady Hands',
  description: 'Generated by khaledssbd',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ConfigProvider theme={mainTheme as any}>
        <body className={jakarta.className}>
          <Provider>
            <AntdRegistry>
              <Toaster
                richColors
                //   position="top-center"
                toastOptions={{
                  style: {
                    // background: "#2ecc71",
                    border: 'none',
                  },
                }}
              />
              {children}
            </AntdRegistry>
          </Provider>
        </body>
      </ConfigProvider>
    </html>
  );
}
